main:
    steps:
    - extract_and_load:
        parallel:
            branches:
            - crashes:
                steps:
                - extract_crashes:
                    call: http.post
                    args:
                        url: https://us-central1-musa509-378614.cloudfunctions.net/extract_crashes
                        auth:
                            type: OIDC
                - prepare_crashes:
                    call: http.post
                    args:
                        url: https://us-central1-musa509-378614.cloudfunctions.net/prepare_crashes
                        auth:
                            type: OIDC
                - load_crashes:
                    call: http.post
                    args:
                        url: https://us-central1-musa509-378614.cloudfunctions.net/load_crashes
                        auth:
                            type: OIDC
            - volume:
                steps:
                    - extract_volume:
                        call: http.post
                        args:
                            url: https://us-central1-musa509-378614.cloudfunctions.net/extract_volume
                            auth:
                                type: OIDC
                    
                    - load_volume:
                        call: http.post
                        args:
                            url: https://us-central1-musa509-378614.cloudfunctions.net/load_volume
                            auth:
                                type: OIDC
    - clean_merge:
        parallel:


    - train_model: {}
